/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc.regolo.jfib;

import org.junit.Test;
import static org.junit.Assert.*;

public class JFibTest {
    @Test
    public void someLibraryMethodReturnsTrue() {
        JFib jfib = new JFib();
        assertEquals(0, jfib.fib(0));
        assertEquals(1, jfib.fib(1));
        assertEquals(1, jfib.fib(2));
        assertEquals(2, jfib.fib(3));
        assertEquals(3, jfib.fib(4));
        assertEquals(5, jfib.fib(5));
        assertEquals(8, jfib.fib(6));
        assertEquals(13, jfib.fib(7));
        assertEquals(21, jfib.fib(8));
        assertEquals(34, jfib.fib(9));
        assertEquals(55, jfib.fib(10));
    }
}
